### PR TITLE
Update for lens 5

### PR DESCRIPTION
**Pull request by Lysxia**

### CODE REVIEW

**Comment by lastland** [comment]
Any cool features from lens 5?

**Comment by Lysxia** [comment]
No idea; it's just that there is no upper bound on lens, and since I am building with cabal instead of stack, it pulled the latest version, and I got a build error without this patch.

**Comment by Lysxia** [comment]
Uh oh, I forgot all the `examples` are still pinned to GHC 8.4, so we can't upgrade from the `lts-12` resolver yet. It should be possible to build this with `lts-12` by listing the new dependencies of `lens` in `stack.yaml`.

**Comment by Lysxia** [comment]
Actually we weren't using that instance, and removing it makes the code compatible with more versions of lens.

**Comment by lastland** [comment]
That's convenient!

**Pull request merged**
