### PR TITLE
make hyperlinks point to `plclub` repo version

### PR DESCRIPTION
**Pull request by quinn-dougherty**
at the moment of opening this PR I only went through `quickstart.rst` to update hyperlinks to point to `plclub/` github account's version of repo (off from `antalsz`). I can try updating more files before we merge this in, feel free to leave it open for a while to increase the probability that I do that. Also anyone else can feel free to push to this branch if they see hyperlinks in other files.

### CODE REVIEW

**Comment by lastland** [comment]
@quinn-dougherty Thanks for all these changes. I'll merge this when you feel it's in a state to be merged.

**Comment by lastland** [comment]
> [module index](https://hs-to-coq.readthedocs.io/en/latest/py-modindex.html) is hyperlinked at the bottom of the docs and goes nowhere. Where should it point? or should the hyperlink just be deleted?

I'm not sure about this one, either. Maybe we should just remove this.

**Comment by lastland** [comment]
@quinn-dougherty Since there are not many updates in the past few days, perhaps I should merge this PR?

**Comment by quinn-dougherty** [comment]
roger that, please do! Haven't seen anything else in the docs lately.

**Comment by lastland** [comment]
Thank you!

**Pull request merged**
